baseURL = 'https://fnd.works/'
languageCode = 'en-us'
title = 'fnd.works'
[params]
  Name = "fnd.works"
  HeaderUsername = "guest"
  HeaderHostname = "fnd.works"
  About = "Hi I'm Aleksandar Stojanov - DevOps/Cloud Engineer at NION and this is my website."
  ProfilePicture = "images/profile.jpeg"
  GithubID = "losisin"
  LinkedInID = "losisin"
  # MediumID = "aleksandarstojanov"
  Email = "me@fnd.works"
# [menu]
#   [[menu.header]]
#     name = "about"
#     weight = 1
#     url = "about"
#   [[menu.header]]
#     name = "blog"
#     weight = 2
#     url = "blog"
